sonar.projectKey=LibrarySystem
sonar.projectName=Library System
sonar.projectVersion=1.0
sonar.sources=src/main
sonar.java.binaries=.
sonar.host.url=http://localhost:9000
sonar.login=sqp_76e3023c9981b6ecebe42c9a23e33984722ebb97
sonar.sourceEncoding=UTF-8